Mission/fu you20/m1.2
sdutacm-lcl-internship/internship-mission-work pull request #20
Opened 2023-07-17 11:25 UTC by FuYou20

2023-07-17 12:14 UTC, acmsdut commented on works/guoChengYin/M1.2/main.py
> +    sys.stderr.write('no such handle' + "\n"+'ErrorCode '+str(status_code)+"\n")
这个可以不输出额外的消息

2023-07-17 12:17 UTC, acmsdut requested changes
1. 看起来额外做了多用户的功能，不错，但是可以拆分一下，思考题版本额外单开一个文件，主代码按任务要求的来（也就是单个用户）
2. 可以格式化下代码，多处代码风格不统一

2023-07-18 01:58 UTC, kiriecode commented
cool!

2023-07-18 02:02 UTC, acmsdut requested changes
总结的非常好。很全面👍🏻

程序上还有两个问题：
1. 用户存在、用户不存在这几个 case 请按任务要求上的数据结构来（也就是和 M1.1 一样），不要输出额外的内容
2. 代码可以格式化一下（用 IDE 自带的功能即可）

2023-07-18 12:28 UTC, acmsdut requested changes
还是那个问题没解决哦
看一下M1.1的描述，输出格式要对应

2023-07-18 13:27 UTC, acmsdut approved these changes
Accepted

2023-07-18 13:28 UTC, merged