Mission/my only snow/m1.1
sdutacm-lcl-internship/internship-mission-work pull request #26
Opened 2023-07-17 13:28 UTC by MyOnlySnow

2023-07-17 13:31 UTC, acmsdut commented
也不用每次新开一个 PR，有修改直接提交在原分支就好

2023-07-17 13:34 UTC, acmsdut requested changes
`SlavicG` 这个 case 返回的 rank 不对，应为 `expert`

2023-07-17 13:35 UTC, MyOnlySnow commented
我以为得返回底下那个，就改成这样了，悲桑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sdutacm-lcl-internship/internship-mission-work"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月17日(星期一) 晚上9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sdutacm-lcl-internship/internship-mission-work] Mission/my only snow/m1.1 (PR #26)





 
@acmsdut requested changes on this pull request.
 
SlavicG 这个 case 返回的 rank 不对，应为 expert
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-07-17 15:34 UTC, acmsdut requested changes
功能没什么问题，可以再格式化一下代码

2023-07-18 02:06 UTC, acmsdut approved these changes
Accepted

2023-07-18 02:07 UTC, merged