M2.1 first commit
sdutacm-lcl-internship/internship-mission-work pull request #29
Opened 2023-07-18 07:45 UTC by xiandandd

2023-07-18 08:07 UTC, kiriecode commented
cool !

2023-07-18 08:43 UTC, acmsdut commented
总结的很好！大家也可以来学习下

2023-07-18 09:48 UTC, acmsdut requested changes

2023-07-18 09:48 UTC, acmsdut commented on works/xiandandd/M2.1/main.py
> +            "message": "无法访问api，请尝试检查网络"
经测试很多时候进到这个 except 的都是 `Expecting value: line 1 column 1 (char 0)` 报错

2023-07-18 09:48 UTC, acmsdut commented on works/xiandandd/M2.1/main.py
> +        elif number == 500:
这一类是目标服务器500，应该归为 type 2。type 4 是指你自己的代码运行时异常，跑到了 except

2023-07-18 09:48 UTC, acmsdut commented on works/xiandandd/M2.1/main.py
> +        # 如果content-type不在请求头里面，说明这个响应异常了，应该是这样吧
也可以这么判断把，但只是一小类极端情况，即：响应收到了，但内容不符合标准HTTP协议（通常网站都不会出现这种case，除非是自己写的没实现完全的 http server 或被劫持的 DIY 响应）。可以测试一下试试什么时候会已出现。

type 3 主要是无效响应（网络错误、请求超时等，大多数都根本收不到任何响应的时候）

2023-07-18 10:03 UTC, acmsdut commented on works/xiandandd/M2.1/main.py
> +            "message": "无法访问api，请尝试检查网络"
一次性多几个用户或者多次请求就会容易复现

2023-07-18 11:25 UTC, MeiK2333 commented
相当 nice

2023-07-18 13:43 UTC, acmsdut requested changes

2023-07-19 02:37 UTC, acmsdut approved these changes
Accepted (First Blood)

2023-07-19 02:38 UTC, merged