Mission/baobaojiao/m2.3
sdutacm-lcl-internship/internship-mission-work pull request #38
Opened 2023-07-19 08:53 UTC by baobaojiao

cf_spider5__M2.3

2023-07-19 09:33 UTC, cooper-xs commented
别的不说 您是真迅速

2023-07-20 10:44 UTC, acmsdut requested changes
测试发现似乎 ratings 没走缓存，每次请求都会走一遍爬取

2023-07-20 11:07 UTC, baobaojiao commented
> 测试发现似乎 ratings 没走缓存，每次请求都会走一遍爬取
debug的时候接口忘了调回来了，现在可以了

2023-07-20 11:29 UTC, acmsdut commented
测试这个会直接500挂掉：
`http://127.0.0.1:2333/getUserRatings?handle=Sanya161616_`

2023-07-20 16:25 UTC, acmsdut approved these changes
Accepted

2023-07-20 16:25 UTC, merged