Mission/fu you20/m2.2
sdutacm-lcl-internship/internship-mission-work pull request #43
Opened 2023-07-20 01:56 UTC by FuYou20

试一试

2023-07-20 08:38 UTC, acmsdut requested changes
完成度不错，目前主要只有时间格式化那一个问题，改一下把

2023-07-20 08:38 UTC, acmsdut commented on works/guoChengYin/M2.2/myapp.py
> +          context_info["ratingUpdatedAt"] = iso_datetime_str + '+08:00'
<img width="519" alt="image" src="https://github.com/sdutacm-lcl-internship/internship-mission-work/assets/64129971/e9126418-a82c-44b6-b37c-48b9d85096e9">
时间有点问题，我再 utc+0 下测试拿到的结果不对

2023-07-20 16:28 UTC, acmsdut requested changes

2023-07-20 16:28 UTC, acmsdut commented on works/guoChengYin/M2.2/myapp.py
> +          dt_object = datetime.fromtimestamp(item["ratingUpdateTimeSeconds"],pytz.timezone('Asia/Shanghai'))
程序在这里抛出异常了，仔细检查下呢

2023-07-21 01:52 UTC, FuYou20 commented on works/guoChengYin/M2.2/myapp.py
> +          dt_object = datetime.fromtimestamp(item["ratingUpdateTimeSeconds"],pytz.timezone('Asia/Shanghai'))
学长，这个时间转换这块这里我试了几次并没发现异常。但是，发现如果请求的比较频繁有时候这个API接口会返回一个HTML，这时候再用json.loads()解析就会报错。我在这检测了一下抛出了一个请求异常

2023-07-21 02:54 UTC, acmsdut commented on works/guoChengYin/M2.2/myapp.py
> +          dt_object = datetime.fromtimestamp(item["ratingUpdateTimeSeconds"],pytz.timezone('Asia/Shanghai'))
嗯，那个一般是 503，就是访问太频繁 CF 的服务可能临时宕机的 case

2023-07-21 03:03 UTC, acmsdut requested changes

2023-07-21 03:03 UTC, acmsdut commented on works/guoChengYin/M2.2/myapp.py
> +    if api_res is None or isinstance(e, requests.exceptions.ConnectionError):
这个判断有问题，比如上面代码里出现了一些逻辑异常导致 api_res 为 None（如 `加一行 1/0`），也会走到 502，而不是下面的 500 分支

2023-07-21 03:14 UTC, acmsdut approved these changes
Accepted

2023-07-21 03:14 UTC, merged