Mission/baobaojiao/m3.1
sdutacm-lcl-internship/internship-mission-work pull request #49
Opened 2023-07-21 09:15 UTC by baobaojiao

2023-07-21 10:10 UTC, dreamerblue commented
![IMG_8529](https://github.com/sdutacm-lcl-internship/internship-mission-work/assets/19774268/c778f54c-0cd8-444e-91e2-2002a0ba7503)

悠着点做啊喂！

2023-07-22 10:45 UTC, acmsdut commented
1. 文件应始终只有最多两个（`data-user-info.xxx` 和 `data-user-ratings.xxx`），具体数据怎么存自定义就好。每条 handle 相关的记录都要有对应的时间戳，如请求发现 handle1 过期，那么就爬取 handle1，并将新数据更新回文件（写入新数据到文件对应位置，其他无关的行不修改）。
2. 返回内容（响应体、状态码）还是要和之前的一样，现在所有请求都返回了一个 `{ "message": "ok" }`

2023-07-22 10:45 UTC, acmsdut requested changes
需要修改

2023-07-26 14:50 UTC, acmsdut commented
@baobaojiao ding~ 有后续修改吗

2023-07-28 03:56 UTC, acmsdut requested changes
返回内容（响应体、状态码）还是要和之前的一样，现在所有请求都返回了一个 { "message": "ok" }

2023-07-29 01:25 UTC, acmsdut requested changes
功能没什么问题，但响应体的数据结构多了一个字段 `out_time`，需去除

2023-07-29 01:39 UTC, acmsdut approved these changes
Accepted

2023-07-29 01:40 UTC, merged