Mission/fu you20/m2.4
sdutacm-lcl-internship/internship-mission-work pull request #52
Opened 2023-07-22 00:29 UTC by FuYou20

2023-07-25 04:22 UTC, acmsdut requested changes
1. 传入 `handles=a&handles=b` 时 500
2. 传入 `handles[0]` `handles[]` 等情况时获取参数不对
3. JSON 格式时，如果 `handles` 不是数组（如数字、字符串、null 等）则会 500

2023-07-25 11:46 UTC, FuYou20 commented
> 1. 确定`handles=a&handles=b`时500
> 2. 确定`handles[0]` `handles[]`等情况时获取参数
> 3. JSON格式时，如果`handles`不是吞吐量（如数字、字符串、null等） 500

学长，1和2两种传参的格式都要支持吗。现在只支持1这种格式，2这种格式会将'['识别为字符串的一部分

2023-07-25 12:16 UTC, acmsdut commented
> > 1. 确定`handles=a&handles=b`时500
> > 2. 确定`handles[0]` `handles[]`等情况时获取参数
> > 3. JSON格式时，如果`handles`不是吞吐量（如数字、字符串、null等） 500
> 
> 学长，1和2两种传参的格式都要支持吗。现在只支持1这种格式，2这种格式会将'['识别为字符串的一部分

嗯是的，题面上那三种都要测试下

2023-07-26 09:39 UTC, acmsdut commented
JSON 格式时，如果 handles 不是数组（如数字、字符串、null 等）依然返回 200，期望返回 400

2023-07-26 14:46 UTC, acmsdut approved these changes
Accepted

2023-07-26 14:46 UTC, merged