mission/xiandandd/M3.2
sdutacm-lcl-internship/internship-mission-work pull request #57
Opened 2023-07-24 09:43 UTC by xiandandd

2023-07-28 04:43 UTC, acmsdut requested changes
1. 可以改一下，尽量不要使用 delete，而是当数据存在时，使用 UPDATE 更新
2. 在打开外键约束后，程序会报错，可以试试，以及思考下如何解决呢（可以在 connect 后使用 `db.execute("PRAGMA foreign_keys = ON")` 开启）

2023-07-28 04:43 UTC, acmsdut commented on works/xiandandd/M3.2/M32.py
> +                   rating_updated_at NOT NULL,
rating_updated_at 为什么没有类型呢

2023-07-31 03:47 UTC, acmsdut requested changes

2023-07-31 03:47 UTC, acmsdut commented on works/xiandandd/M3.2/M32.py
> +        response = requests.get(url, params=params)
这几行是在做什么呢，看起来空跑了一个请求？

2023-07-31 08:26 UTC, xiandandd commented on works/xiandandd/M3.2/M32.py
> +        response = requests.get(url, params=params)
> 这几行是在做什么呢，看起来空跑了一个请求？

因为如果只进行rating查询，往rating表里面插入新数据的时候，如果info表里面没有这个人的数据的话就会报外键错误问题，所以先进行一下info请求，把数据插入info，然后再进行rating的插入

2023-08-03 14:43 UTC, acmsdut commented
@xiandandd 这个再修改下呢？

2023-08-04 04:53 UTC, acmsdut requested changes
那个 flag+han 的实现方式有点暴力了，不是很好

为什么不抽离一下 query handle 函数呢（比如 `query_user_info(handles)`）？在路由解析好参数后，以及处理外键的地方都调用它

2023-08-04 08:14 UTC, acmsdut approved these changes
Accepted

2023-08-04 08:14 UTC, merged