Mission/fu you20/m4.1
sdutacm-lcl-internship/internship-mission-work pull request #76
Opened 2023-08-04 11:51 UTC by FuYou20

2023-08-05 01:07 UTC, acmsdut requested changes
1. 在无网络等情况下，没有合适的错误提示
2. 优化建议:
   1. 初始和无 rating 时隐藏表头
   2. 用户名可以仿一下 CF 的基于 rank 分段的颜色样式，而非固定深蓝色

2023-08-05 01:07 UTC, acmsdut commented on works/guoChengYin/M4.1/templates/index.html
> +    $.ajax({
对于 4.1，应该使用 xhr 或 fetch，不要使用第三方库来实现功能

2023-08-06 15:40 UTC, acmsdut requested changes
1. 在无网络等情况下，没有合适的错误提示
2. \>=3000 首字母应为黑色

2023-08-07 08:07 UTC, FuYou20 commented
> 1. 在无网络等情况下，没有合适的错误提示

> 2. >=3000 首字母应为黑色



> 1. 在无网络等情况下，没有合适的错误提示
> 2. >=3000 首字母应为黑色
![image](https://github.com/sdutacm-lcl-internship/internship-mission-work/assets/102398004/dbe0c449-6c31-4140-bf9a-c8faaac84393)
学长，这个弹窗是不是之前没显示(或许是浏览器兼容的问题？)。

2023-08-08 07:57 UTC, acmsdut requested changes
<img width="332" alt="image" src="https://github.com/sdutacm-lcl-internship/internship-mission-work/assets/64129971/1bec8ef7-e54b-4122-98ca-49a3deb335a9">

\>=3000 时名字样式不对，应为首字母黑色，其他部分红色。

可以使用 css 的 `::first-letter` 选择器来做

另一个问题：`package.json` 等文件应局限在你自己的作业目录内，不应该影响到根目录（如不需要可删除）

2023-08-10 02:15 UTC, acmsdut approved these changes
Accepted

2023-08-10 02:15 UTC, merged